version: 2
jobs:
  linux:
    docker:
      - image: norionomura/swift:swift-4.2-branch
    steps:
      - checkout
      - run:
          name: Build
          command: swift build -c release
      - run:
          name: Test
          command: swift test
  macos:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Tools
          command: |
            brew install swiftlint
            bundle config build.sqlite3 --with-sqlite3-dir=/opt/local
      - run:
          name: Install dependencies
          command: |
            bundle check || bundle install --path vendor/bundle
      - run:
          name: Linting
          command: |
            swiftlint
      - run:
          name: Run tests
          command: |
            swift package generate-xcodeproj
            xcodebuild test -scheme xcodeproj-Package -enableCodeCoverage YES
      - run:
          name: Send test coverage report
          command: |
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  version: 2
  linux-and-macos:
    jobs:
      - linux
      - macos
